services:
  app:
    build:
      context: .
      dockerfile: runtime/Dockerfile
    env_file:
      - .env
    environment:
      OTEL_PHP_AUTOLOAD_ENABLED: "true"
      OTEL_SERVICE_NAME: php-fpm-slim-auto
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_PROPAGATORS: baggage,tracecontext

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    depends_on:
      - app
    ports:
      - "8080:8080"
